# Generated by Django 3.2.8 on 2021-10-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, verbose_name='Javob')),
                ('image', models.ImageField(blank=True, upload_to='answers_img/', verbose_name='rasmi')),
                ('true_answer', models.BooleanField(verbose_name='togrimi')),
            ],
        ),
        migrations.CreateModel(
            name='LogicQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Mantiqiy Savol')),
                ('answer', models.TextField(blank=True, verbose_name="Javob (to'ldirish shartmas)")),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2150, verbose_name='Savol')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiya')),
                ('tel_num', models.PositiveIntegerField(verbose_name='telfon raqami')),
                ('unique_field', models.CharField(blank=True, editable=False, max_length=30, verbose_name='Bir martalik parol')),
                ('times', models.CharField(blank=True, choices=[('ERTALABKI', 'ertalabki'), ('KECHKI', 'kechki')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon fontaosem')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_answer', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('logic_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.logicquiz')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='main.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='main.user')),
                ('user_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.answer')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='ways',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='way_quizz', to='main.ways'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.quiz'),
        ),
    ]
