# Generated by Django 3.2.8 on 2021-10-20 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicquiz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 20, 16, 11, 30, 820335, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
